device: cuda
exp_num: 3
path: "/home/meet/FlowMatchingTests/conditional-flow-matching/neural_operator/exps/ks_high_res/mod_FM_exps"
th_seed: 786
np_seed: 786

model:
  blocks_dim_lst: [[256, 256, 128], [128, 128, 128], [128, 128, 128], [128, 128, 128] ,[128, 256, 256]]
  embedding_mlp_lst: [1, 3, 3]
  cond_mult: 4
  act_func: RELU

FM:
  sigma: 1e-2
  sigma_min: 1e-3
  scale: 5
  return_noise: False

dataloader:
  datapath: "/home/meet/FlowMatchingTests/conditional-flow-matching/neural_operator/data/ks_high_res.npy"
  split_ratio: 0.8
  train_batch_size: 1024
  test_batch_size: 128

optimizer:
  lr: 1e-3

num_epochs: 10_000
print_epoch_int: 10
save_epoch_int: 100
print_with_epoch_int: 128
restart: False
restart_epoch: