device: cuda
exp_num: 6
path: "/home/meet/FlowMatchingTests/conditional-flow-matching/physics_flow_matching/multi_pretrain/exps/wm_vf"
th_seed: 786
np_seed: 786

unet:
  dim: [3, 32, 32]
  out_channels: 3
  num_channels: 256
  channel_mult: null
  res_blocks: 8
  head_chans: 64
  attn_res: "64"
  dropout: 0.0
  new_attn: True
  film: True

dataloader:
  wm_paths: [["/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_wall_pressure_all_out.npy",
            "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_wall_dudy_all_out.npy",
            "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_wall_dwdy_all_out.npy"]]
  vf_paths: [["/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_u_y40_all_out.npy",
            "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_v_y40_all_out.npy",
            "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_w_y40_all_out.npy"]]
  # wm_paths: ['/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/small_piece/wall_pressure_small.npy', 
  #           "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/small_piece/wall_dudy_small.npy",
  #           "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/small_piece/wall_dwdy_small.npy"]
  # vf_paths: ["/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/small_piece/u5_small.npy",
  #           "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/small_piece/v5_small.npy",
  #           "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/small_piece/w5_small.npy"]
  batch_size: 128
  time_cutoff: 36000
  cutoff: 40
  jump: 4
  patch_dims : [32, 32]
  dataset: WMVF_P
  
optimizer:
  lr: 1e-4

scheduler:
  T_max: 100
  eta_min: 1e-6

num_epochs: 500
print_epoch_int: 1
save_epoch_int: 5
print_with_epoch_int: 10
# rolling_steps: 3
restart: False
restart_epoch: