device: cuda
exp_num: 2
path: "/home/meet/FlowMatchingTests/conditional-flow-matching/physics_flow_matching/wm_ar/exps"
th_seed: 786
np_seed: 786

unet:
  dim: [1, 160, 200]
  num_channels: 128
  res_blocks: 2
  head_chans: 64
  attn_res: "40,20"
  dropout: 0.0
  new_attn: True
  film: True

dataloader:
  wm_paths: ['/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_wall_dudy_41-220_out.npy'] 
  v_0_150_path: "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_v_y5-150_41-220_out.npy"
  v_int_paths: ['/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_v_y10_41-220_out.npy',
              '/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_v_y40_41-220_out.npy',
              '/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_v_y60_41-220_out.npy',
              '/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_v_y70_41-220_out.npy',
              '/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_v_y80_41-220_out.npy',
              '/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_v_y100_41-220_out.npy']
  batch_size: 8
  cutoff: 160
  dataset: WMAR

optimizer:
  lr: 1e-4

scheduler:
  T_max: 100
  eta_min: 1e-6

num_epochs: 100
print_epoch_int: 1
save_epoch_int: 5
print_with_epoch_int: 10
restart: False
restart_epoch: