device: cuda
exp_num: 3
path: "/home/meet/FlowMatchingTests/conditional-flow-matching/physics_flow_matching/wm_vf/exps"
th_seed: 786
np_seed: 786

unet:
  dim: [3, 160, 200]
  out_channels: 2
  num_channels: 128
  channel_mult: [1, 2]
  res_blocks: 2
  head_chans: 64
  attn_res: "40,20"
  dropout: 0.2
  new_attn: True
  film: True

dataloader:
  wppath: "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_wall_pressure_41-220_out.npy"
  ws_u_path: "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_wall_dudy_41-220_out.npy"
  ws_w_path: "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_wall_dwdy_41-220_out.npy"
  vel_y: "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_w_y5-150_41-220_out.npy"
  batch_size: 8
  cutoff: 160
  y_norm_dict: {0: 5, 1: 150}
  dataset: WMVF

optimizer:
  lr: 1e-4

scheduler:
  T_max: 100
  eta_min: 1e-6

num_epochs: 100
print_epoch_int: 1
save_epoch_int: 5
print_with_epoch_int: 10
restart: False
restart_epoch: