device: cuda
exp_num: 1
path: "/home/meet/FlowMatchingTests/conditional-flow-matching/physics_flow_matching/multi_pretrain/exps/wm_vf"
th_seed: 786
np_seed: 786

unet:
  dim: [3, 160, 200]
  out_channels: 3
  num_channels: 128
  channel_mult: null
  res_blocks: 2
  head_chans: 64
  attn_res: "40,20"
  dropout: 0.2
  new_attn: True
  film: True

dataloader:
  wm_paths: ["/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_wall_pressure_all_out.npy",
            "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_wall_dudy_all_out.npy",
            "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_wall_dwdy_all_out.npy"]
  vf_paths: ["/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_u_y5_all_out.npy",
            "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_v_y5_all_out.npy",
            "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_w_y5_all_out.npy"]
  # wm_paths: ['/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/small_piece/wall_pressure_small.npy', 
  #           "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/small_piece/wall_dudy_small.npy",
  #           "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/small_piece/wall_dwdy_small.npy"]
  # vf_paths: ["/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/small_piece/u5_small.npy",
  #           "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/small_piece/v5_small.npy",
  #           "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/small_piece/w5_small.npy"]
  batch_size: 8
  time_cutoff: 4500
  cutoff: 160
  dataset: WMVF_M

optimizer:
  lr: 1e-4

scheduler:
  T_max: 100
  eta_min: 1e-6

num_epochs: 10
print_epoch_int: 1
save_epoch_int: 1
print_with_epoch_int: 10
restart: False
restart_epoch: