device: cuda
exp_num: 2
path: "/home/meet/FlowMatchingTests/conditional-flow-matching/physics_flow_matching/wall_pres/exps/FM_exps"
th_seed: 786
np_seed: 786

unet:
  dim: [1, 160, 200]
  num_channels: 128
  res_blocks: 2
  head_chans: 64
  attn_res: "40,20"
  dropout: 0.2
  new_attn: True
  film: True

FM:
  sigma: 1e-2
  return_noise: False

dataloader:
  datapath: "/home/meet/FlowMatchingTests/conditional-flow-matching/physics_flow_matching/wall_pres/data/data_small.npy"
  batch_size: 10

optimizer:
  lr: 1e-4

scheduler:
  T_max: 100
  eta_min: 1e-6

num_epochs: 20_000
print_epoch_int: 1
save_epoch_int: 10
print_with_epoch_int: 128
restart: False
restart_epoch: