device: cuda
exp_num: 1
path: "/home/meet/FlowMatchingTests/conditional-flow-matching/physics_flow_matching/vf_fm/exps"
th_seed: 786
np_seed: 786

unet:
  dim: [3, 320, 200]
  channel_mult: "1,  2,  4,  4"
  num_channels: 128
  res_blocks: 2
  head_chans: 64
  attn_res: "40"
  dropout: 0.0
  new_attn: True
  film: True

FM:
  sigma: 1e-2
  return_noise: False

dataloader:
  datapath: ["/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_u_y20_all_out.npy",
            "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_v_y20_all_out.npy",
            "/home/xiantao/case/wall_pressure/bigchannel/data/to_meet/channel_180_w_y20_all_out.npy"]
  batch_size: 10
  jump: 1
  dataset: VF_FM

optimizer:
  lr: 1e-4

scheduler:
  T_max: 100
  eta_min: 1e-6

num_epochs: 100
print_epoch_int: 1
save_epoch_int: 5
print_with_epoch_int: 10
restart: False
restart_epoch: