device: cuda
exp_num: 2
path: "/home/meet/FlowMatchingTests/conditional-flow-matching/neural_operator/exps/ks_noise_inj"
th_seed: 786
np_seed: 786

model:
  blocks_dim_lst: [[32, 64, 64], [64, 64, 64], [64, 64, 64], [64, 64, 64], [64, 64, 32]]
  act_func: RELU

dataloader:
  datapath: "/home/meet/FlowMatchingTests/conditional-flow-matching/neural_operator/data/ks_data.npy"
  split_ratio: 0.8
  train_batch_size: 256
  test_batch_size: 64
  sigma: 1e-3

optimizer:
  lr: 1e-3

num_epochs: 10_000
print_epoch_int: 10
save_epoch_int: 100
print_with_epoch_int: 128
restart: False
restart_epoch: None