device: cuda
exp_num: 3
path: "/home/meet/FlowMatchingTests/conditional-flow-matching/neural_operator/exps/ks_high_res_noise_inj/noise_inj_exps"
th_seed: 786
np_seed: 786

model:
  blocks_dim_lst: [[256, 256, 128], [128, 128, 128], [128, 128, 128], [128, 256, 256]]
  act_func: RELU

dataloader:
  datapath: "/home/meet/FlowMatchingTests/conditional-flow-matching/neural_operator/data/ks_high_res.npy"
  split_ratio: 0.8
  train_batch_size: 1024
  test_batch_size: 128
  sigma: 1e-3

optimizer:
  lr: 1e-3

num_epochs: 10_000
print_epoch_int: 10
save_epoch_int: 100
print_with_epoch_int: 100
restart: False
restart_epoch: None